[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
indicatif = "0.17.0"
rayon = "1.5.3"
ultraviolet = { version = "0.9.0", features = ["f64"] }
